name: Daily Site Ping

permissions:
  contents: write

on:
  schedule:
    - cron: '0 4 * * *' # runs daily at 10 AM BD time
  workflow_dispatch:

jobs:
  ping-sites:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run site check script
        run: node hitav.js

      - name: Commit report to main branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update daily site status"
          branch: main
          file_pattern: index.html style.css
