name: Daily Site Ping

permissions:
  contents: write

on:
  schedule:
    - cron: '0 2 * * *' # 08 AM BD (UTC+6)
  workflow_dispatch:   # also allow manual trigger

jobs:
  ping-sites:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run site check script
        run: node hitav.js

      - name: Commit updated dashboard
        run: |
          git config --global user.name "Deboraj-roy"
          git config --global user.email "deborajroy123@gmail.com"
          git add index.html style.css reports/
          git commit -m "Update daily site status" || echo "No changes to commit"
          git push origin main
